### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by dragosm** [VarboxInternational/varbox-issues#3]
- Varbox Version: 1.x

### What are you trying to achieve (screenshots might help):

I’ve downloaded the free version of Varbox wanting to start a new project using this platform, but I cannot make it work.

I’ve setup a git repo with the Varbox source code, but it doesn’t seem to be a working Laravel project (eg. it doesn’t have an `.env` file, `php artisan` doesn’t work).

Does anyone know how can I properly install it?

Thanks!

**Comment by zbiller** [comment]
You shouldn't attempt to use Varbox as a monolithic application.

Varbox has been designed as a **Composer package** which you'll have to locally require in your own Laravel projects, so that means you'll need to already have a working Laravel projects on top of which to install Varbox.

<img width="1223" alt="Installation - Varbox - The Free Laravel Admin Panel 2020-09-08 21-22-54" src="https://user-images.githubusercontent.com/2579306/92513855-a3892600-f219-11ea-8705-baed439c9d0e.png">

Please follow the documentation (I suggest installing it in the automatic way, as it's less time consuming): [https://varbox.io/docs/1.x/installation](https://varbox.io/docs/1.x/installation)
